### ISSUE TITLE
update with an eslint config

### ISSUE THREAD

**Issue by kamikazechaser** [forfuturellc/javascript#2]
I was thinking we could update this repo with a definitive eslint config which can be used in our projects/editors.

cc/ @GochoMugo

**Comment by GochoMugo** [comment]
@kamikazechaser *There are too many things to do to spend time formatting code.* I highly suggest we use [prettier](https://prettier.io) to automatically format our code.

**Comment by kamikazechaser** [comment]
Yeah I guess prettier is better. It has not been playing well with me, but I should reconfigure it!
